import './globals.css';
import type { Metadata } from 'next';
// Components
import Nav from '@/components/nav';
// font
import { dosis } from '@/utils/font';

export const metadata: Metadata = {
  title: 'ABDELRHMAN (MOV)',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className='dark'>
        <div className="flex flex-col items-center w-full dark:bg-[#212323] dark:text-[#ededed]">
          <Nav />
          <main className={dosis.className}>{children}</main>
        </div>
      </body>
    </html>
  );
}
