import './globals.css';
import type { Metadata } from 'next';
// Components
import Nav from '@/components/nav';
// font
import { teko } from '@/utils/font';

export const metadata: Metadata = {
  title: 'ABDELRHMAN (MOV)',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="">
        {/* space gradient background */}
        <div
          className="flex flex-col items-center w-full text-slate-50 relative"
          style={{
            // space gradient background
            background: 'fixed radial-gradient(#041f3d, #07070c)',
          }}
        >
          <Nav />
          <main className={`relative md:pl-32 md:w-full z-0 ${teko.className}`}>{children}</main>
        </div>
      </body>
    </html>
  );
}
